### ISSUE TITLE
dear vishvAsa vAsuki - Need your contact info. sir. please help 🙏🙏🙏

### ISSUE THREAD

**Issue by vasubv** [vishvAsa/vedAH#209]
hello @vvasuki 

First of all my anEka praNams for anchoring this mighty project. I'm originally from Bangalore and very much interested in vedic studies. 

I wanted to talk to you briefly, I know your number is not published, i tried sending an email some months back but dont recollect now where i sent. I might have accidentally deleted. So i decided to raise an issue here. Please forgive, since this sinnot appropriate, but this is the only way aDiyEn could reach you. So please excuese me. please spare some time and help aDiyEn 🙏🙏🙏

Please share your phone number or if you are not comfortable, please call me on my whatsapp on **1-504-908-6168**. I live in Dallas Central time zone.

please call me sir. Let me know a time which is convenient for you

**dAsaH
Belakavadi vasudevan (Vasu)
whatsapp - US (504-908-6168)**

**Comment by vvasuki** [comment]
नमस्काराः!

https://vishvasa.github.io/intro/contact/

also will ping you on whatsapp.

**Comment by vasubv** [comment]
ok sir @vvasuki - please ping on WhatsApp - +1-504-908-6168
